import jsPDF from 'jspdf';

interface PollResult {
  poll_id: string;
  question: string;
  option_a: string;
  option_b: string;
  total_votes: number;
  votes_a: number;
  votes_b: number;
  percent_a: number;
  percent_b: number;
}

interface DemoRow {
  segment_type: string;
  segment_value: string;
  choice: string;
  vote_count: number;
}

interface CommonArgs {
  campaignName: string;
  brandName?: string | null;
}

interface OverviewArgs extends CommonArgs {
  results: PollResult[];
}
interface PollsArgs extends CommonArgs {
  results: PollResult[];
}
interface DemoArgs extends CommonArgs {
  results: PollResult[];
  demos: DemoRow[];
}
interface NarrativeArgs extends CommonArgs {
  insights: string;
  results: PollResult[];
}

const BRAND_RED: [number, number, number] = [220, 38, 38];
const TEXT_DARK: [number, number, number] = [17, 17, 17];
const TEXT_MUTED: [number, number, number] = [115, 115, 115];
const BORDER: [number, number, number] = [230, 230, 230];
const GREEN: [number, number, number] = [34, 197, 94];
const BLUE: [number, number, number] = [59, 130, 246];

interface Ctx {
  doc: jsPDF;
  pageW: number;
  pageH: number;
  margin: number;
  y: number;
}

function makeCtx(): Ctx {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  return {
    doc,
    pageW: doc.internal.pageSize.getWidth(),
    pageH: doc.internal.pageSize.getHeight(),
    margin: 40,
    y: 40,
  };
}

function ensureSpace(ctx: Ctx, needed: number) {
  if (ctx.y + needed > ctx.pageH - 60) {
    addFooter(ctx);
    ctx.doc.addPage();
    ctx.y = ctx.margin;
  }
}

function addFooter(ctx: Ctx) {
  ctx.doc.setFontSize(8);
  ctx.doc.setTextColor(...TEXT_MUTED);
  ctx.doc.text(
    `Generated by Versa · ${new Date().toLocaleDateString()}`,
    ctx.margin,
    ctx.pageH - 24
  );
  const pageNum = ctx.doc.getCurrentPageInfo().pageNumber;
  ctx.doc.text(`Page ${pageNum}`, ctx.pageW - ctx.margin, ctx.pageH - 24, { align: 'right' });
}

function drawCover(ctx: Ctx, sectionLabel: string, campaignName: string, brandName?: string | null) {
  const { doc, pageW, margin } = ctx;
  doc.setFillColor(...BRAND_RED);
  doc.rect(0, 0, pageW, 6, 'F');
  ctx.y = 80;
  doc.setFontSize(10);
  doc.setTextColor(...BRAND_RED);
  doc.setFont('helvetica', 'bold');
  doc.text('VERSA', margin, ctx.y);
  ctx.y += 8;
  doc.setFontSize(9);
  doc.setTextColor(...TEXT_MUTED);
  doc.setFont('helvetica', 'normal');
  doc.text(sectionLabel, margin, ctx.y + 4);
  ctx.y += 50;
  doc.setFontSize(26);
  doc.setTextColor(...TEXT_DARK);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(campaignName, pageW - margin * 2);
  doc.text(titleLines, margin, ctx.y);
  ctx.y += titleLines.length * 30;
  if (brandName) {
    ctx.y += 4;
    doc.setFontSize(13);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont('helvetica', 'normal');
    doc.text(brandName, margin, ctx.y);
    ctx.y += 20;
  }
  ctx.y += 16;
  doc.setDrawColor(...BORDER);
  doc.line(margin, ctx.y, pageW - margin, ctx.y);
  ctx.y += 24;
}

function drawBar(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  label: string,
  pct: number,
  color: [number, number, number]
) {
  doc.setFontSize(9);
  doc.setTextColor(17, 17, 17);
  doc.setFont('helvetica', 'normal');
  const truncated = label.length > 30 ? label.slice(0, 30) + '…' : label;
  doc.text(truncated, x, y + 8);
  const barX = x + 140;
  const barW = width - 140 - 50;
  const barH = 10;
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(barX, y, barW, barH, 3, 3, 'F');
  doc.setFillColor(...color);
  doc.roundedRect(barX, y, barW * (pct / 100), barH, 3, 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.text(`${pct}%`, x + width, y + 8, { align: 'right' });
}

function safeFile(name: string, suffix: string) {
  const safe = name.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  return `versa-${safe}-${suffix}.pdf`;
}

// =================== OVERVIEW PDF ===================
export function exportOverviewPdf({ campaignName, brandName, results }: OverviewArgs) {
  const ctx = makeCtx();
  const { doc, pageW, margin } = ctx;
  drawCover(ctx, 'Overview Report', campaignName, brandName);

  const totalVotes = results.reduce((s, r) => s + Number(r.total_votes || 0), 0);
  const avgPerPoll = results.length ? Math.round(totalVotes / results.length) : 0;
  const sorted = [...results].sort((a, b) => b.total_votes - a.total_votes);
  const topPoll = sorted[0];

  // KPIs
  const kpis = [
    { label: 'Polls', value: String(results.length) },
    { label: 'Total votes', value: totalVotes.toLocaleString() },
    { label: 'Avg per poll', value: avgPerPoll.toLocaleString() },
    { label: 'Top vote count', value: (topPoll?.total_votes ?? 0).toLocaleString() },
  ];
  const cardW = (pageW - margin * 2 - 24) / 4;
  kpis.forEach((kpi, i) => {
    const x = margin + i * (cardW + 8);
    doc.setDrawColor(...BORDER);
    doc.setFillColor(250, 250, 250);
    doc.roundedRect(x, ctx.y, cardW, 64, 6, 6, 'FD');
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont('helvetica', 'normal');
    doc.text(kpi.label.toUpperCase(), x + 10, ctx.y + 18);
    doc.setFontSize(18);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont('helvetica', 'bold');
    doc.text(kpi.value, x + 10, ctx.y + 46);
  });
  ctx.y += 88;

  // Top performing poll
  if (topPoll) {
    ensureSpace(ctx, 80);
    doc.setFontSize(12);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont('helvetica', 'bold');
    doc.text('Top Performing Poll', margin, ctx.y);
    ctx.y += 16;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const ql = doc.splitTextToSize(topPoll.question, pageW - margin * 2);
    doc.text(ql, margin, ctx.y);
    ctx.y += ql.length * 13 + 6;
    const winnerA = topPoll.percent_a >= topPoll.percent_b;
    drawBar(doc, margin, ctx.y, pageW - margin * 2, topPoll.option_a, topPoll.percent_a, winnerA ? GREEN : BLUE);
    ctx.y += 16;
    drawBar(doc, margin, ctx.y, pageW - margin * 2, topPoll.option_b, topPoll.percent_b, !winnerA ? GREEN : BLUE);
    ctx.y += 28;
  }

  // Quick winner snapshot
  ensureSpace(ctx, 40);
  doc.setFontSize(12);
  doc.setTextColor(...TEXT_DARK);
  doc.setFont('helvetica', 'bold');
  doc.text('Quick Winner Snapshot', margin, ctx.y);
  ctx.y += 16;
  results.forEach((r) => {
    ensureSpace(ctx, 28);
    const winner = r.percent_a >= r.percent_b ? r.option_a : r.option_b;
    const margin_pt = Math.abs(r.percent_a - r.percent_b);
    doc.setFontSize(9);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont('helvetica', 'normal');
    const qLines = doc.splitTextToSize(r.question, pageW - margin * 2 - 60);
    doc.text(qLines[0] || '', margin, ctx.y);
    ctx.y += 12;
    doc.setFontSize(10);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont('helvetica', 'bold');
    const wTrunc = winner.length > 50 ? winner.slice(0, 50) + '…' : winner;
    doc.text(wTrunc, margin, ctx.y);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont('helvetica', 'normal');
    doc.text(`+${margin_pt}pt`, pageW - margin, ctx.y, { align: 'right' });
    ctx.y += 14;
    doc.setDrawColor(...BORDER);
    doc.line(margin, ctx.y, pageW - margin, ctx.y);
    ctx.y += 8;
  });

  addFooter(ctx);
  doc.save(safeFile(campaignName, 'overview'));
}

// =================== POLLS PDF ===================
export function exportPollsPdf({ campaignName, brandName, results }: PollsArgs) {
  const ctx = makeCtx();
  const { doc, pageW, margin } = ctx;
  drawCover(ctx, 'Poll Results Report', campaignName, brandName);

  doc.setFontSize(14);
  doc.setTextColor(...TEXT_DARK);
  doc.setFont('helvetica', 'bold');
  doc.text(`All Polls (${results.length})`, margin, ctx.y);
  ctx.y += 18;

  results.forEach((r, idx) => {
    ensureSpace(ctx, 100);
    doc.setDrawColor(...BORDER);
    doc.line(margin, ctx.y, pageW - margin, ctx.y);
    ctx.y += 14;

    doc.setFontSize(11);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont('helvetica', 'bold');
    const qLines = doc.splitTextToSize(`${idx + 1}. ${r.question}`, pageW - margin * 2);
    doc.text(qLines, margin, ctx.y);
    ctx.y += qLines.length * 14;

    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `${r.total_votes.toLocaleString()} votes · ${r.votes_a.toLocaleString()} A / ${r.votes_b.toLocaleString()} B`,
      margin,
      ctx.y
    );
    ctx.y += 14;

    const winnerA = r.percent_a >= r.percent_b;
    drawBar(doc, margin, ctx.y, pageW - margin * 2, r.option_a, r.percent_a, winnerA ? GREEN : BLUE);
    ctx.y += 18;
    drawBar(doc, margin, ctx.y, pageW - margin * 2, r.option_b, r.percent_b, !winnerA ? GREEN : BLUE);
    ctx.y += 22;
  });

  addFooter(ctx);
  doc.save(safeFile(campaignName, 'polls'));
}

// =================== DEMOGRAPHICS PDF ===================
export function exportDemographicsPdf({ campaignName, brandName, results, demos }: DemoArgs) {
  const ctx = makeCtx();
  const { doc, pageW, margin } = ctx;
  drawCover(ctx, 'Demographics Report', campaignName, brandName);

  const totalVotes = results.reduce((s, r) => s + Number(r.total_votes || 0), 0);
  doc.setFontSize(10);
  doc.setTextColor(...TEXT_MUTED);
  doc.setFont('helvetica', 'normal');
  doc.text(`Across ${results.length} polls · ${totalVotes.toLocaleString()} total votes`, margin, ctx.y);
  ctx.y += 18;

  if (!demos.length) {
    doc.setFontSize(11);
    doc.setTextColor(...TEXT_DARK);
    doc.text('No demographic data available yet.', margin, ctx.y);
    addFooter(ctx);
    doc.save(safeFile(campaignName, 'demographics'));
    return;
  }

  const grouped: Record<string, Record<string, { A: number; B: number }>> = {};
  demos.forEach((row) => {
    const k = row.segment_type;
    if (!grouped[k]) grouped[k] = {};
    const seg = row.segment_value || 'Unknown';
    if (!grouped[k][seg]) grouped[k][seg] = { A: 0, B: 0 };
    grouped[k][seg][row.choice as 'A' | 'B'] =
      (grouped[k][seg][row.choice as 'A' | 'B'] || 0) + Number(row.vote_count);
  });

  Object.entries(grouped).forEach(([type, segments]) => {
    ensureSpace(ctx, 50);
    doc.setFontSize(12);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont('helvetica', 'bold');
    doc.text(type.replace(/_/g, ' ').toUpperCase(), margin, ctx.y);
    ctx.y += 16;

    const segTotal = Object.values(segments).reduce((s, c) => s + c.A + c.B, 0);
    Object.entries(segments)
      .sort((a, b) => b[1].A + b[1].B - (a[1].A + a[1].B))
      .forEach(([seg, counts]) => {
        ensureSpace(ctx, 22);
        const total = (counts.A || 0) + (counts.B || 0);
        const pctA = total ? Math.round(((counts.A || 0) / total) * 100) : 0;
        const sharePct = segTotal ? Math.round((total / segTotal) * 100) : 0;

        doc.setFontSize(9);
        doc.setTextColor(...TEXT_DARK);
        doc.setFont('helvetica', 'bold');
        doc.text(seg, margin, ctx.y + 8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...TEXT_MUTED);
        doc.text(`${sharePct}% of segment`, margin + 100, ctx.y + 8);

        const barX = margin + 200;
        const barW = pageW - margin * 2 - 200 - 90;
        const barH = 10;
        doc.setFillColor(240, 240, 240);
        doc.roundedRect(barX, ctx.y + 1, barW, barH, 2, 2, 'F');
        doc.setFillColor(...GREEN);
        doc.roundedRect(barX, ctx.y + 1, barW * (pctA / 100), barH, 2, 2, 'F');
        doc.setFillColor(...BLUE);
        doc.roundedRect(barX + barW * (pctA / 100), ctx.y + 1, barW * ((100 - pctA) / 100), barH, 2, 2, 'F');

        doc.setTextColor(...TEXT_MUTED);
        doc.setFontSize(8);
        doc.text(
          `${pctA}% / ${100 - pctA}% · ${total}`,
          pageW - margin,
          ctx.y + 8,
          { align: 'right' }
        );
        ctx.y += 18;
      });
    ctx.y += 10;
  });

  addFooter(ctx);
  doc.save(safeFile(campaignName, 'demographics'));
}

// =================== NARRATIVE / AI INSIGHTS PDF ===================
export function exportNarrativePdf({ campaignName, brandName, insights, results }: NarrativeArgs) {
  const ctx = makeCtx();
  const { doc, pageW, margin } = ctx;
  drawCover(ctx, 'AI Insights Report', campaignName, brandName);

  const totalVotes = results.reduce((s, r) => s + Number(r.total_votes || 0), 0);
  doc.setFontSize(10);
  doc.setTextColor(...TEXT_MUTED);
  doc.setFont('helvetica', 'normal');
  doc.text(`${results.length} polls · ${totalVotes.toLocaleString()} votes analyzed`, margin, ctx.y);
  ctx.y += 22;

  if (!insights.trim()) {
    doc.setFontSize(11);
    doc.setTextColor(...TEXT_DARK);
    doc.text('No AI insights generated yet. Generate insights in the dashboard first.', margin, ctx.y);
    addFooter(ctx);
    doc.save(safeFile(campaignName, 'ai-insights'));
    return;
  }

  // Strip markdown-ish formatting and render with simple structure
  const lines = insights.split('\n');
  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      ctx.y += 6;
      continue;
    }
    if (/^##\s+/.test(line)) {
      ensureSpace(ctx, 30);
      ctx.y += 6;
      doc.setFontSize(13);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont('helvetica', 'bold');
      doc.text(line.replace(/^##\s+/, ''), margin, ctx.y);
      ctx.y += 18;
    } else if (/^[-*]\s+/.test(line)) {
      ensureSpace(ctx, 18);
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont('helvetica', 'normal');
      const text = line.replace(/^[-*]\s+/, '').replace(/\*\*([^*]+)\*\*/g, '$1');
      const wrapped = doc.splitTextToSize(`• ${text}`, pageW - margin * 2 - 8);
      doc.text(wrapped, margin + 8, ctx.y);
      ctx.y += wrapped.length * 13 + 2;
    } else {
      ensureSpace(ctx, 18);
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_DARK);
      doc.setFont('helvetica', 'normal');
      const text = line.replace(/\*\*([^*]+)\*\*/g, '$1');
      const wrapped = doc.splitTextToSize(text, pageW - margin * 2);
      doc.text(wrapped, margin, ctx.y);
      ctx.y += wrapped.length * 13 + 2;
    }
  }

  addFooter(ctx);
  doc.save(safeFile(campaignName, 'ai-insights'));
}

// Backward-compat: keep old single export but re-route to overview
export function exportCampaignPdf(args: { campaignName: string; brandName?: string | null; results: PollResult[]; demos: DemoRow[] }) {
  exportOverviewPdf({ campaignName: args.campaignName, brandName: args.brandName, results: args.results });
}
