import jsPDF from 'jspdf';

interface PollResult {
  poll_id: string;
  question: string;
  option_a: string;
  option_b: string;
  total_votes: number;
  votes_a: number;
  votes_b: number;
  percent_a: number;
  percent_b: number;
}

interface DemoRow {
  segment_type: string;
  segment_value: string;
  choice: string;
  vote_count: number;
}

interface ExportArgs {
  campaignName: string;
  brandName?: string | null;
  results: PollResult[];
  demos: DemoRow[];
}

const BRAND_RED: [number, number, number] = [220, 38, 38];
const TEXT_DARK: [number, number, number] = [17, 17, 17];
const TEXT_MUTED: [number, number, number] = [115, 115, 115];
const BORDER: [number, number, number] = [230, 230, 230];
const GREEN: [number, number, number] = [34, 197, 94];
const BLUE: [number, number, number] = [59, 130, 246];

export function exportCampaignPdf({ campaignName, brandName, results, demos }: ExportArgs) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 40;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - 60) {
      addFooter();
      doc.addPage();
      y = margin;
    }
  };

  const addFooter = () => {
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(
      `Generated by Versa · ${new Date().toLocaleDateString()}`,
      margin,
      pageH - 24
    );
    const pageNum = doc.getCurrentPageInfo().pageNumber;
    doc.text(`Page ${pageNum}`, pageW - margin, pageH - 24, { align: 'right' });
  };

  // === COVER ===
  doc.setFillColor(...BRAND_RED);
  doc.rect(0, 0, pageW, 6, 'F');

  y = 80;
  doc.setFontSize(10);
  doc.setTextColor(...BRAND_RED);
  doc.setFont('helvetica', 'bold');
  doc.text('VERSA', margin, y);

  y += 8;
  doc.setFontSize(9);
  doc.setTextColor(...TEXT_MUTED);
  doc.setFont('helvetica', 'normal');
  doc.text('Campaign Report', margin, y + 4);

  y += 50;
  doc.setFontSize(28);
  doc.setTextColor(...TEXT_DARK);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(campaignName, pageW - margin * 2);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 32;

  if (brandName) {
    y += 4;
    doc.setFontSize(13);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont('helvetica', 'normal');
    doc.text(brandName, margin, y);
    y += 20;
  }

  y += 16;
  doc.setDrawColor(...BORDER);
  doc.line(margin, y, pageW - margin, y);
  y += 24;

  // KPIs
  const totalVotes = results.reduce((s, r) => s + Number(r.total_votes || 0), 0);
  const avgPerPoll = results.length ? Math.round(totalVotes / results.length) : 0;
  const topPoll = [...results].sort((a, b) => b.total_votes - a.total_votes)[0];

  const kpis = [
    { label: 'Polls', value: String(results.length) },
    { label: 'Total votes', value: totalVotes.toLocaleString() },
    { label: 'Avg per poll', value: avgPerPoll.toLocaleString() },
    { label: 'Top vote count', value: (topPoll?.total_votes ?? 0).toLocaleString() },
  ];

  const cardW = (pageW - margin * 2 - 24) / 4;
  kpis.forEach((kpi, i) => {
    const x = margin + i * (cardW + 8);
    doc.setDrawColor(...BORDER);
    doc.setFillColor(250, 250, 250);
    doc.roundedRect(x, y, cardW, 64, 6, 6, 'FD');
    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont('helvetica', 'normal');
    doc.text(kpi.label.toUpperCase(), x + 10, y + 18);
    doc.setFontSize(18);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont('helvetica', 'bold');
    doc.text(kpi.value, x + 10, y + 46);
  });
  y += 88;

  // === POLL RESULTS ===
  ensureSpace(40);
  doc.setFontSize(14);
  doc.setTextColor(...TEXT_DARK);
  doc.setFont('helvetica', 'bold');
  doc.text('Poll Results', margin, y);
  y += 18;

  results.forEach((r, idx) => {
    ensureSpace(90);
    doc.setDrawColor(...BORDER);
    doc.line(margin, y, pageW - margin, y);
    y += 14;

    doc.setFontSize(11);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont('helvetica', 'bold');
    const qLines = doc.splitTextToSize(`${idx + 1}. ${r.question}`, pageW - margin * 2);
    doc.text(qLines, margin, y);
    y += qLines.length * 14;

    doc.setFontSize(8);
    doc.setTextColor(...TEXT_MUTED);
    doc.setFont('helvetica', 'normal');
    doc.text(`${r.total_votes.toLocaleString()} votes`, margin, y);
    y += 14;

    const winnerA = r.percent_a >= r.percent_b;
    drawBar(doc, margin, y, pageW - margin * 2, r.option_a, r.percent_a, winnerA ? GREEN : BLUE);
    y += 18;
    drawBar(doc, margin, y, pageW - margin * 2, r.option_b, r.percent_b, !winnerA ? GREEN : BLUE);
    y += 22;
  });

  // === DEMOGRAPHICS ===
  if (demos.length > 0) {
    ensureSpace(40);
    y += 10;
    doc.setFontSize(14);
    doc.setTextColor(...TEXT_DARK);
    doc.setFont('helvetica', 'bold');
    doc.text('Demographics', margin, y);
    y += 18;

    const grouped: Record<string, Record<string, { A: number; B: number }>> = {};
    demos.forEach((row) => {
      const k = row.segment_type;
      if (!grouped[k]) grouped[k] = {};
      const seg = row.segment_value || 'Unknown';
      if (!grouped[k][seg]) grouped[k][seg] = { A: 0, B: 0 };
      grouped[k][seg][row.choice as 'A' | 'B'] =
        (grouped[k][seg][row.choice as 'A' | 'B'] || 0) + Number(row.vote_count);
    });

    Object.entries(grouped).forEach(([type, segments]) => {
      ensureSpace(50);
      doc.setFontSize(10);
      doc.setTextColor(...TEXT_MUTED);
      doc.setFont('helvetica', 'bold');
      doc.text(type.replace(/_/g, ' ').toUpperCase(), margin, y);
      y += 14;

      Object.entries(segments)
        .sort((a, b) => b[1].A + b[1].B - (a[1].A + a[1].B))
        .forEach(([seg, counts]) => {
          ensureSpace(20);
          const total = (counts.A || 0) + (counts.B || 0);
          const pctA = total ? Math.round(((counts.A || 0) / total) * 100) : 0;
          doc.setFontSize(9);
          doc.setTextColor(...TEXT_DARK);
          doc.setFont('helvetica', 'normal');
          doc.text(seg, margin, y + 8);

          const barX = margin + 100;
          const barW = pageW - margin * 2 - 100 - 80;
          const barH = 8;
          doc.setFillColor(240, 240, 240);
          doc.roundedRect(barX, y + 2, barW, barH, 2, 2, 'F');
          doc.setFillColor(...GREEN);
          doc.roundedRect(barX, y + 2, barW * (pctA / 100), barH, 2, 2, 'F');

          doc.setTextColor(...TEXT_MUTED);
          doc.setFontSize(8);
          doc.text(
            `${pctA}% / ${100 - pctA}% · ${total}`,
            pageW - margin,
            y + 8,
            { align: 'right' }
          );
          y += 16;
        });
      y += 8;
    });
  }

  addFooter();

  const safeName = campaignName.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  doc.save(`versa-${safeName}-report.pdf`);
}

function drawBar(
  doc: jsPDF,
  x: number,
  y: number,
  width: number,
  label: string,
  pct: number,
  color: [number, number, number]
) {
  doc.setFontSize(9);
  doc.setTextColor(17, 17, 17);
  doc.setFont('helvetica', 'normal');
  const truncated = label.length > 30 ? label.slice(0, 30) + '…' : label;
  doc.text(truncated, x, y + 8);

  const barX = x + 140;
  const barW = width - 140 - 50;
  const barH = 10;
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(barX, y, barW, barH, 3, 3, 'F');
  doc.setFillColor(...color);
  doc.roundedRect(barX, y, barW * (pct / 100), barH, 3, 3, 'F');

  doc.setFont('helvetica', 'bold');
  doc.text(`${pct}%`, x + width, y + 8, { align: 'right' });
}
