type PollImageSide = 'A' | 'B';

const pollImageModules = import.meta.glob('../assets/polls/*.{png,jpg,jpeg,webp,avif}', {
  eager: true,
  import: 'default',
}) as Record<string, string>;

const localPollImages = Object.fromEntries(
  Object.entries(pollImageModules).map(([path, url]) => [path.split('/').pop()!.toLowerCase(), url])
);

const QUESTION_SIDE_ALIASES: Record<string, Partial<Record<PollImageSide, string>>> = {
  'cairo or dubai': { A: 'cairo.jpg', B: 'dubai-visit.jpg' },
  'careem or uber': { A: 'careem.jpg', B: 'uber.png' },
  'iftar at home or restaurant': { A: 'iftar-home.jpg', B: 'fancy-restaurant.jpg' },
  'local brand or international brand': { A: 'local-brand.jpg', B: 'international-brand.jpg' },
  'egyptian film or hollywood': { A: 'egyptian-series.jpg', B: 'cinema.jpg' },
  'henna night or modern bachelor party': { A: 'night.jpg', B: 'going-out.png' },
  'city stars or mall of arabia': { A: 'city-stars-mall.jpg', B: 'mall-of-arabia.jpg' },
  'thobe or suit for events': { A: 'thobe.jpg', B: 'suit.jpg' },
  'thobe or suit': { A: 'thobe.jpg', B: 'suit.jpg' },
  'iphone or samsung': { A: 'iphone.jpg', B: 'samsung.jpg' },
  'clubhouse or x spaces': { A: 'clubhouse.jpg', B: 'x-spaces.jpg' },
  'spotify or anghami': { A: 'spotify.jpg', B: 'anghami.jpg' },
  'netflix or shahid': { A: 'netflix.jpg', B: 'shahid.jpg' },
  'x or threads': { A: 'x-twitter.jpg', B: 'threads.jpg' },
  'vodafone or etisalat': { A: 'vodafone.jpg', B: 'etisalat.jpg' },
  'zoom or google meet': { A: 'zoom.jpg', B: 'google-meet.jpg' },
  'notion or google docs': { A: 'notion.jpg', B: 'google-docs.jpg' },
  'talabat or elmenus': { A: 'talabat.jpg', B: 'elmenus.jpg' },
  'mercedes or audi': { A: 'mercedes.jpg', B: 'audi.jpg' },
  'kfc or popeyes': { A: 'kfc.jpg', B: 'popeyes.jpg' },
  'converse or vans': { A: 'converse.jpg', B: 'vans.jpg' },
  'zara or h m': { A: 'zara.jpg', B: 'hm.jpg' },
  'playstation or xbox': { A: 'playstation.jpg', B: 'xbox.jpg' },
  'nike or adidas': { A: 'nike.jpg', B: 'adidas.jpg' },
  'pepsi or coca cola': { A: 'pepsi.jpg', B: 'coca-cola.jpg' },
  'bmw or mercedes': { A: 'bmw.jpg', B: 'mercedes.jpg' },
  'toyota or bmw': { A: 'toyota.jpg', B: 'bmw.jpg' },
  'rolex or casio': { A: 'rolex.jpg', B: 'casio.jpg' },
  'louis vuitton or gucci': { A: 'louis-vuitton.jpg', B: 'gucci.jpg' },
  'mcdonald s or burger king': { A: 'mcdonalds.jpg', B: 'burger-king.jpg' },
  'noon or amazon': { A: 'noon-brand.jpg', B: 'amazon.jpg' },
  'starbucks or local coffee': { A: 'starbucks.jpg', B: 'turkish-coffee.jpg' },
  'costa or starbucks': { A: 'coffee.jpg', B: 'starbucks.jpg' },
  'tiktok or instagram': { A: 'tiktok.jpg', B: 'instagram.jpg' },
  'youtube or tiktok': { A: 'youtube.jpg', B: 'tiktok.jpg' },
  'whatsapp or telegram': { A: 'whatsapp.jpg', B: 'telegram.jpg' },
  'snapchat or ig stories': { A: 'snapchat.jpg', B: 'instagram.jpg' },
  'bereal or instagram': { A: 'bereal.jpg', B: 'instagram.jpg' },
  'adidas or puma': { A: 'adidas.jpg', B: 'puma.jpg' },
  'sony or bose': { A: 'playstation.jpg', B: 'bose.jpg' },
  'hilton or marriott': { A: 'hilton.jpg', B: 'hotel.jpg' },
  'airbnb or hotel': { A: 'airbnb.jpg', B: 'hotel.jpg' },
  'heels or flats': { A: 'heels.jpg', B: 'flats.jpg' },
  'aviator or wayfarer': { A: 'aviator.jpg', B: 'wayfarer.jpg' },
  'backpack or tote': { A: 'backpack.jpg', B: 'tote.jpg' },
  'gouna or ain sokhna': { A: 'gouna.jpg', B: 'ain-sokhna.jpg' },
  'gouna or sahel': { A: 'gouna.jpg', B: 'sahel.jpg' },
  'sahel or ain sokhna': { A: 'sahel.jpg', B: 'ain-sokhna.jpg' },
  'dahab or sharm': { A: 'beach.jpg', B: 'ain-sokhna.jpg' },
  'capsule or collection': { A: 'capsule-wardrobe.jpg', B: 'thrift.jpg' },
  'oversized or fitted': { A: 'oversized.jpg', B: 'smart-casual.jpg' },
  'monochrome or colors': { A: 'monochrome.jpg', B: 'thrift.jpg' },
  'denim or leather': { A: 'denim.jpg', B: 'designer-bag.jpg' },
  'sneakers or dress shoes': { A: 'sneakers.jpg', B: 'dress-shoes.jpg' },
  'loungewear or dress up': { A: 'loungewear.jpg', B: 'designer.jpg' },
  'gold or silver': { A: 'rolex.jpg', B: 'silver-jewelry.jpg' },
  'linkedin or tiktok': { A: 'linkedin.jpg', B: 'tiktok.jpg' },
  'save or spend now': { A: 'financial-freedom.jpg', B: 'shopping.jpg' },
  'insurance or invest': { A: 'insurance.jpg', B: 'stocks.jpg' },
  'thrift or brand new': { A: 'thrift.jpg', B: 'brand-store.jpg' },
  'eco friendly or luxury brand': { A: 'eco-friendly.jpg', B: 'branded.jpg' },
  'marina or sahel': { A: 'marina.jpg', B: 'sahel.jpg' },
  // Fix duplicate pairs
  'swvl or microbus': { A: 'swvl-v2.jpg', B: 'microbus-v2.jpg' },
  'alarm or body clock': { A: 'alarm-clock-v2.jpg', B: 'body-clock-v2.jpg' },
  'phone alarm or sunrise wake up': { A: 'alarm-clock-v2.jpg', B: 'sunrise.jpg' },
  'hire a maid or do it yourself': { A: 'maid-service-v2.jpg', B: 'diy-cleaning-v2.jpg' },
  'hire maid or do it yourself': { A: 'maid-service-v2.jpg', B: 'diy-cleaning-v2.jpg' },
  'hijab fashion or abaya style': { A: 'hijab-fashion-v2.jpg', B: 'abaya-v2.jpg' },
  'souq fridays or black friday': { A: 'souq.jpg', B: 'black-friday.jpg' },
  'souq friday or black friday': { A: 'souq.jpg', B: 'black-friday.jpg' },
  'buy now or wait for sale': { A: 'shopping.jpg', B: 'souq.jpg' },
  'gift cards or pick the gift': { A: 'gift-card.jpg', B: 'pick-gift.jpg' },
  'shawerma el reem or bab el hara': { A: 'shawarma.jpg', B: 'falafel.jpg' },
  // Apps & Tech - ensure distinct sides
  '5g or wi fi': { A: 'vodafone.jpg', B: 'wifi.jpg' },
  'airpods or galaxy buds': { A: 'airpods.jpg', B: 'samsung.jpg' },
  'bluetooth speaker or headphones': { A: 'bose.jpg', B: 'airpods.jpg' },
  'cloud storage or hard drive': { A: 'chatgpt.jpg', B: 'wfh.jpg' },
  'dark mode or light mode': { A: 'chatgpt.jpg', B: 'iphone.jpg' },
  'e book or physical book': { A: 'iphone.jpg', B: 'books.jpg' },
  'fawry or instapay': { A: 'fawry.jpg', B: 'instapay.jpg' },
  'gaming console or gaming pc': { A: 'playstation.jpg', B: 'wfh.jpg' },
  'ipad or samsung tab': { A: 'iphone.jpg', B: 'samsung.jpg' },
  'macbook or windows laptop': { A: 'iphone.jpg', B: 'wfh.jpg' },
  'online courses or university': { A: 'linkedin.jpg', B: 'books.jpg' },
  'online gaming or mobile gaming': { A: 'playstation.jpg', B: 'iphone.jpg' },
  'podcast or radio': { A: 'spotify.jpg', B: 'bose.jpg' },
  'smart tv or projector': { A: 'cinema.jpg', B: 'netflix.jpg' },
  'tablet or laptop for travel': { A: 'iphone.jpg', B: 'wfh.jpg' },
  'two phones or one': { A: 'samsung.jpg', B: 'iphone.jpg' },
  'stc or zain': { A: 'stc.jpg', B: 'zain.jpg' },
  'electric car or petrol': { A: 'bmw.jpg', B: 'toyota.jpg' },
  'face id or fingerprint': { A: 'iphone.jpg', B: 'samsung.jpg' },
  'drone or action camera': { A: 'chatgpt.jpg', B: 'camping.jpg' },
  'qr code payment or cash': { A: 'iphone.jpg', B: 'financial-freedom.jpg' },
  'paypal or apple pay': { A: 'financial-freedom.jpg', B: 'iphone.jpg' },
  'linkedin or networking events': { A: 'linkedin.jpg', B: 'going-out.png' },
  'tech minimalist or gadget lover': { A: 'nature.jpg', B: 'iphone.jpg' },
  'chatgpt or google search': { A: 'chatgpt.jpg', B: 'google-maps.jpg' },
  'crypto wallet or bank account': { A: 'crypto.jpg', B: 'financial-freedom.jpg' },
  'netflix or cinema': { A: 'netflix.jpg', B: 'cinema.jpg' },
  'osn or netflix': { A: 'shahid.jpg', B: 'netflix.jpg' },
  'jumia or noon': { A: 'shopping.jpg', B: 'noon-brand.jpg' },
  'instashop or breadfast': { A: 'instashop.png', B: 'breadfast.png' },
  'dell or hp laptop': { A: 'wfh.jpg', B: 'linkedin.jpg' },
  'apple or samsung ecosystem': { A: 'iphone.jpg', B: 'samsung.jpg' },
  // Brands - ensure distinct sides
  'canon or sony camera': { A: 'camping.jpg', B: 'bose.jpg' },
  'costa coffee or tim hortons': { A: 'coffee.jpg', B: 'starbucks.jpg' },
  'domino s or local pizza': { A: 'pizza.jpg', B: 'falafel.jpg' },
  'dyson or local brand': { A: 'ikea.jpg', B: 'local-brand.jpg' },
  'gopro or phone camera': { A: 'camping.jpg', B: 'phone-camera.jpg' },
  'lego or local toys': { A: 'playstation.jpg', B: 'local-brand.jpg' },
  'moleskine or any notebook': { A: 'books.jpg', B: 'wfh.jpg' },
  'ray ban or oakley': { A: 'ray-ban.jpg', B: 'aviator.jpg' },
  'samsung tv or lg': { A: 'samsung.jpg', B: 'cinema.jpg' },
  'under armour or reebok': { A: 'gym.jpg', B: 'sneakers.jpg' },
  'versace or dolce gabbana': { A: 'versace.jpg', B: 'designer-bag.jpg' },
  'weber or local grill': { A: 'grilled.jpg', B: 'falafel.jpg' },
  'wework or home office': { A: 'linkedin.jpg', B: 'wfh.jpg' },
  'baskin robbins or local gelato': { A: 'ice-cream.jpg', B: 'kunafa.jpg' },
  'lululemon or nike for gym': { A: 'gym.jpg', B: 'nike.jpg' },
  'north face or local outdoor brand': { A: 'mountains.jpg', B: 'local-brand.jpg' },
  'sephora or local beauty shop': { A: 'hijab-fashion.jpg', B: 'local-brand.jpg' },
  'nespresso or turkish coffee pot': { A: 'coffee.jpg', B: 'turkish-pot.jpg' },
  'uniqlo or zara basics': { A: 'hm.jpg', B: 'zara.jpg' },
  'uber eats or talabat': { A: 'uber-eats.jpg', B: 'talabat.jpg' },
  'jordan or yeezy': { A: 'nike.jpg', B: 'adidas.jpg' },
  'ikea or local furniture': { A: 'ikea.jpg', B: 'local-brand.jpg' },
  'airbnb or hotel chain': { A: 'airbnb.jpg', B: 'hotel.jpg' },
  // Cairo & MENA Local
  'abu dhabi or dubai': { A: 'abu-dhabi.jpg', B: 'dubai-visit.jpg' },
  'ahly or zamalek': { A: 'ahly.jpg', B: 'cairo.jpg' },
  'alexandria or sahel': { A: 'alexandria.jpg', B: 'sahel.jpg' },
  'arabic music or english music': { A: 'cairo.jpg', B: 'linkedin.jpg' },
  'arabic or english at work': { A: 'cairo.jpg', B: 'linkedin.jpg' },
  'drive or metro in cairo': { A: 'driving.jpg', B: 'metro.jpg' },
  'egyptian dialect or khaleeji': { A: 'egyptian-series.jpg', B: 'dubai-visit.jpg' },
  'egyptian series or turkish series': { A: 'egyptian-series.jpg', B: 'turkish-series.jpg' },
  'egyptian street food or restaurant': { A: 'falafel.jpg', B: 'fancy-restaurant.jpg' },
  'egyptian wedding or destination': { A: 'big-wedding.jpg', B: 'fly.jpg' },
  'eid shopping or eid travel': { A: 'shopping.jpg', B: 'fly.jpg' },
  'felucca or nile cruise': { A: 'felucca.jpg', B: 'nile-cruise.jpg' },
  'friday brunch or sahel weekend': { A: 'fancy-restaurant.jpg', B: 'sahel.jpg' },
  'henna night or bachelor party': { A: 'night.jpg', B: 'going-out.png' },
  'kunafa or basbousa': { A: 'kunafa.jpg', B: 'dates.jpg' },
  'live in dubai or just visit': { A: 'dubai-visit.jpg', B: 'fly.jpg' },
  'local brand or international trust': { A: 'local-brand.jpg', B: 'international-brand.jpg' },
  'maadi or heliopolis': { A: 'cairo.jpg', B: 'compound.jpg' },
  'new cairo or zamalek': { A: 'compound.jpg', B: 'cairo.jpg' },
  'nile cruise or beach resort': { A: 'nile-cruise.jpg', B: 'ain-sokhna.jpg' },
  'private school or public school': { A: 'compound.jpg', B: 'books.jpg' },
  'ramadan nights out or stay home': { A: 'going-out.png', B: 'home-dinner.jpg' },
  'riyadh or jeddah': { A: 'abu-dhabi.jpg', B: 'dubai-visit.jpg' },
  'sobia or qamar el din': { A: 'dates.jpg', B: 'kunafa.jpg' },
  // Eat & Drink
  'breakfast or dinner person': { A: 'croissant.jpg', B: 'fancy-restaurant.jpg' },
  'brunch culture or skip to lunch': { A: 'croissant.jpg', B: 'grilled.jpg' },
  'buffet or la carte': { A: 'buffet.jpg', B: 'a-la-carte.jpg' },
  'buffet or a la carte': { A: 'buffet.jpg', B: 'a-la-carte.jpg' },
  'chai karak or cappuccino': { A: 'chai-karak.jpg', B: 'coffee.jpg' },
  'cook with recipe or improvise': { A: 'books.jpg', B: 'cooking.jpg' },
  'cooking show fan or food vlogger': { A: 'netflix.jpg', B: 'tiktok.jpg' },
  'croissant or mana eesh': { A: 'croissant.jpg', B: 'manaeesh.jpg' },
  'dark chocolate or milk': { A: 'dark-chocolate.jpg', B: 'milk-chocolate.jpg' },
  'dates or chocolate': { A: 'dates.jpg', B: 'chocolate.jpg' },
  'delivery or dine in': { A: 'talabat.jpg', B: 'fancy-restaurant.jpg' },
  'eat alone or always with people': { A: 'coffee.jpg', B: 'fancy-restaurant.jpg' },
  'eat healthy or eat happy': { A: 'falafel.jpg', B: 'pizza.jpg' },
  'eat out or cook at home': { A: 'fancy-restaurant.jpg', B: 'cooking.jpg' },
  'falafel or hummus': { A: 'falafel.jpg', B: 'hummus.jpg' },
  'food market or supermarket': { A: 'falafel.jpg', B: 'shopping.jpg' },
  'food truck or restaurant': { A: 'falafel.jpg', B: 'fancy-restaurant.jpg' },
  'foul or eggs for breakfast': { A: 'foul.jpg', B: 'eggs.jpg' },
  'grilled or fried chicken': { A: 'grilled.jpg', B: 'fried.jpg' },
  'hardee s or mcdonald s': { A: 'hardees.jpg', B: 'mcdonalds.jpg' },
  'homemade juice or bottled': { A: 'dates.jpg', B: 'pepsi.jpg' },
  'hot chocolate or matcha': { A: 'chocolate.jpg', B: 'matcha.jpg' },
  'ice cream or kunafa': { A: 'ice-cream.jpg', B: 'kunafa.jpg' },
  'iced coffee or hot coffee': { A: 'starbucks.jpg', B: 'turkish-coffee.jpg' },
  'koshary or shawarma': { A: 'koshary.jpg', B: 'shawarma.jpg' },
  'lebanese or egyptian food': { A: 'hummus.jpg', B: 'koshary.jpg' },
  'leftovers or always fresh': { A: 'home-dinner.jpg', B: 'grilled.jpg' },
  'manakeesh or croissant': { A: 'manaeesh.jpg', B: 'croissant.jpg' },
  'meal prep or cook fresh daily': { A: 'home-dinner.jpg', B: 'cooking.jpg' },
  'molten chocolate or kunafa': { A: 'chocolate.jpg', B: 'kunafa.jpg' },
  'nuts or chips for a snack': { A: 'dates.jpg', B: 'chips.jpg' },
  'protein shake or fresh juice': { A: 'gym.jpg', B: 'dates.jpg' },
  'restaurant with view or hidden gem': { A: 'fancy-restaurant.jpg', B: 'falafel.jpg' },
  'sahlab or hot chocolate': { A: 'turkish-coffee.jpg', B: 'chocolate.jpg' },
  'seafood or red meat': { A: 'seafood.jpg', B: 'grilled.jpg' },
  'skip breakfast or never': { A: 'coffee.jpg', B: 'croissant.jpg' },
  'smoothie bowl or cereal': { A: 'dates.jpg', B: 'croissant.jpg' },
  'sparkling water or still': { A: 'starbucks.jpg', B: 'nature.jpg' },
  'spicy or mild': { A: 'grilled.jpg', B: 'hummus.jpg' },
  'starbucks or local coffee shop': { A: 'starbucks.jpg', B: 'turkish-coffee.jpg' },
  'street food or fine dining': { A: 'falafel.jpg', B: 'fancy-restaurant.jpg' },
  'sugar or sugar free': { A: 'kunafa.jpg', B: 'dates.jpg' },
  'sushi or pizza': { A: 'sushi.jpg', B: 'pizza.jpg' },
  'takeaway or eat in': { A: 'talabat.jpg', B: 'fancy-restaurant.jpg' },
  'tea or coffee': { A: 'tea.jpg', B: 'coffee.jpg' },
  'turkish coffee or espresso': { A: 'turkish-coffee.jpg', B: 'coffee.jpg' },
  'vegan meal or meat lover': { A: 'falafel.jpg', B: 'grilled.jpg' },
  'water or soft drink with food': { A: 'nature.jpg', B: 'pepsi.jpg' },
  // Everyday Life
  'beach vacation or mountain trip': { A: 'beach.jpg', B: 'mountains.jpg' },
  'big wedding or intimate wedding': { A: 'big-wedding.jpg', B: 'intimate-wedding.jpg' },
  'camping or hotel': { A: 'camping.jpg', B: 'hotel.jpg' },
  'city life or suburb life': { A: 'city.jpg', B: 'compound.jpg' },
  'compound or city apartment': { A: 'compound.jpg', B: 'city-apartment.jpg' },
  'cook for guests or cater': { A: 'cooking.jpg', B: 'fancy-restaurant.jpg' },
  'cook or order in on weekdays': { A: 'cooking.jpg', B: 'order-in.jpg' },
  'couple workout or solo': { A: 'gym.jpg', B: 'outdoor-workout.jpg' },
  'dog person or cat person': { A: 'dogs.jpg', B: 'cats.jpg' },
  'drive or be driven': { A: 'driving.jpg', B: 'uber.png' },
  'early riser or night owl': { A: 'sunrise.jpg', B: 'night-sky.jpg' },
  'gym or outdoor workout': { A: 'gym.jpg', B: 'outdoor-workout.jpg' },
  'homebody or always out': { A: 'home-dinner.jpg', B: 'going-out.png' },
  'hot shower or cold shower': { A: 'nature.jpg', B: 'beach.jpg' },
  'introvert or extrovert': { A: 'books.jpg', B: 'going-out.png' },
  'journal or mental notes': { A: 'books.jpg', B: 'iphone.jpg' },
  'large friend group or small circle': { A: 'going-out.png', B: 'coffee.jpg' },
  'learn a language or new skill': { A: 'language.jpg', B: 'linkedin.jpg' },
  'meditation or just sleep more': { A: 'nature.jpg', B: 'night-sky.jpg' },
  'minimalist or maximalist home': { A: 'nature.jpg', B: 'branded.jpg' },
  'morning person or night person': { A: 'sunrise.jpg', B: 'night.jpg' },
  'move abroad or stay home': { A: 'move-abroad.jpg', B: 'home-dinner.jpg' },
  'multitask or single focus': { A: 'wfh.jpg', B: 'books.jpg' },
  'music while working or silence': { A: 'spotify.jpg', B: 'books.jpg' },
  'news junkie or news detox': { A: 'news-junkie.jpg', B: 'nature.jpg' },
  'paper planner or digital calendar': { A: 'books.jpg', B: 'iphone.jpg' },
  'read or watch': { A: 'books.jpg', B: 'cinema.jpg' },
  'road trip or fly': { A: 'driving.jpg', B: 'fly.jpg' },
  'routine or spontaneous': { A: 'suit.jpg', B: 'fly.jpg' },
  'solo travel or group trip': { A: 'alone-shopping.jpg', B: 'going-out.png' },
  'staycation or travel vacation': { A: 'home-dinner.jpg', B: 'fly.jpg' },
  'strict schedule or flexible day': { A: 'suit.jpg', B: 'wfh.jpg' },
  'text or call': { A: 'iphone.jpg', B: 'samsung.jpg' },
  'travel light or pack everything': { A: 'fly.jpg', B: 'pack-everything.jpg' },
  'walk everywhere or always drive': { A: 'nature.jpg', B: 'driving.jpg' },
  'work from home or office': { A: 'wfh.jpg', B: 'suit.jpg' },
  'apartment with garden or penthouse': { A: 'compound.jpg', B: 'city-apartment.jpg' },
  // Shopping
  'black friday fan or normal prices': { A: 'black-friday.jpg', B: 'mall.jpg' },
  'branded or unbranded': { A: 'branded.jpg', B: 'shopping.jpg' },
  'buy in bulk or as needed': { A: 'buy-bulk.jpg', B: 'shopping.jpg' },
  'cash on delivery or prepay': { A: 'shopping.jpg', B: 'iphone.jpg' },
  'compare prices or buy trusted': { A: 'iphone.jpg', B: 'brand-store.jpg' },
  'duty free shopping or local': { A: 'duty-free.jpg', B: 'souq.jpg' },
  'eco friendly products or cheapest': { A: 'eco-friendly.jpg', B: 'shopping.jpg' },
  'grocery list or freestyle': { A: 'grocery-list.jpg', B: 'shopping.jpg' },
  'impulse buyer or researcher': { A: 'shopping.jpg', B: 'books.jpg' },
  'local market or hypermarket': { A: 'souq.jpg', B: 'shopping.jpg' },
  'loyalty programs worth it': { A: 'branded.jpg', B: 'shopping.jpg' },
  'mall or street shopping': { A: 'mall.jpg', B: 'souq.jpg' },
  'new arrivals or classics': { A: 'brand-store.jpg', B: 'capsule-wardrobe.jpg' },
  'one big purchase or many small': { A: 'branded.jpg', B: 'shopping.jpg' },
  'online or in store shopping': { A: 'iphone.jpg', B: 'mall.jpg' },
  'return often or keep everything': { A: 'shopping.jpg', B: 'branded.jpg' },
  'reviews first or just buy': { A: 'iphone.jpg', B: 'shopping.jpg' },
  'same day delivery or free shipping': { A: 'talabat.jpg', B: 'noon-brand.jpg' },
  'second hand or always new': { A: 'thrift.jpg', B: 'brand-store.jpg' },
  'shop alone or with friends': { A: 'alone-shopping.jpg', B: 'going-out.png' },
  'souq deals or brand store': { A: 'souq.jpg', B: 'brand-store.jpg' },
  'subscribe and save or one time buy': { A: 'iphone.jpg', B: 'shopping.jpg' },
  'try before buying or trust online': { A: 'mall.jpg', B: 'iphone.jpg' },
  'unboxing matters or nah': { A: 'branded.jpg', B: 'shopping.jpg' },
  'window shop or buy on sight': { A: 'window-shop.jpg', B: 'shopping.jpg' },
  'wishlists or spontaneous picks': { A: 'iphone.jpg', B: 'shopping.jpg' },
  'brand loyalty or best deal': { A: 'branded.jpg', B: 'souq.jpg' },
  // Spending & Money
  'budget or spend freely': { A: 'financial-freedom.jpg', B: 'shopping.jpg' },
  'buy a car or invest the money': { A: 'bmw.jpg', B: 'stocks.jpg' },
  'buy apartment or start a business': { A: 'real-estate.jpg', B: 'wfh.jpg' },
  'buy latest phone yearly': { A: 'iphone.jpg', B: 'samsung.jpg' },
  'buy new or used car': { A: 'bmw.jpg', B: 'toyota.jpg' },
  'cash or card': { A: 'financial-freedom.jpg', B: 'iphone.jpg' },
  'co founder or solo founder': { A: 'linkedin.jpg', B: 'wfh.jpg' },
  'designer bag or travel trip': { A: 'designer-bag.jpg', B: 'fly.jpg' },
  'emergency fund or yolo fund': { A: 'insurance.jpg', B: 'shopping.jpg' },
  'fancy restaurant or home dinner': { A: 'fancy-restaurant.jpg', B: 'home-dinner.jpg' },
  'finance a car or pay cash': { A: 'bmw.jpg', B: 'financial-freedom.jpg' },
  'financial advisor or self taught': { A: 'linkedin.jpg', B: 'books.jpg' },
  // Style
  'balenciaga or off white': { A: 'balenciaga.jpg', B: 'off-white.jpg' },
  'black outfit or colors': { A: 'monochrome.jpg', B: 'thrift.jpg' },
  'branded gym wear or plain': { A: 'nike.jpg', B: 'gym.jpg' },
  'buy original or inspired': { A: 'branded.jpg', B: 'thrift.jpg' },
  'capsule wardrobe or variety': { A: 'capsule-wardrobe.jpg', B: 'thrift.jpg' },
  'denim jacket or leather jacket': { A: 'denim.jpg', B: 'designer-bag.jpg' },
  'designer sunglasses or regular': { A: 'ray-ban.jpg', B: 'wayfarer.jpg' },
  'follow trends or own style': { A: 'follow-trends.jpg', B: 'monochrome.jpg' },
  'gold jewelry or silver': { A: 'rolex.jpg', B: 'silver-jewelry.jpg' },
  'minimal makeup or full glam': { A: 'natural-beauty.jpg', B: 'designer.jpg' },
  'ounass or farfetch': { A: 'branded.jpg', B: 'designer-bag.jpg' },
};

const OPTION_ALIASES: Record<string, string> = {
  // Apps & Tech
  dubai: 'dubai-visit.jpg',
  uber: 'uber.png',
  careem: 'careem.jpg',
  iphone: 'iphone.jpg',
  samsung: 'samsung.jpg',
  android: 'samsung.jpg',
  'samsung tab': 'samsung.jpg',
  ipad: 'iphone.jpg',
  macbook: 'iphone.jpg',
  windows: 'wfh.jpg',
  whatsapp: 'whatsapp.jpg',
  telegram: 'telegram.jpg',
  tiktok: 'tiktok.jpg',
  instagram: 'instagram-v2.jpg',
  'ig stories': 'instagram.jpg',
  snapchat: 'snapchat.jpg',
  spotify: 'spotify.jpg',
  anghami: 'anghami.jpg',
  netflix: 'netflix.jpg',
  shahid: 'shahid.jpg',
  osn: 'shahid.jpg',
  youtube: 'youtube.jpg',
  talabat: 'talabat.jpg',
  elmenus: 'elmenus.jpg',
  instashop: 'instashop.png',
  breadfast: 'breadfast.png',
  noon: 'noon-brand.jpg',
  amazon: 'amazon.jpg',
  jumia: 'noon-brand.jpg',
  'google maps': 'google-maps.jpg',
  waze: 'waze.jpg',
  zoom: 'zoom.jpg',
  'google meet': 'google-meet.jpg',
  vodafone: 'vodafone.jpg',
  etisalat: 'etisalat.jpg',
  stc: 'stc.jpg',
  zain: 'zain.jpg',
  chatgpt: 'chatgpt.jpg',
  google: 'google-maps.jpg',
  'apple watch': 'rolex.jpg',
  'classic watch': 'casio.jpg',
  airpods: 'airpods.jpg',
  'galaxy buds': 'samsung.jpg',
  playstation: 'playstation.jpg',
  xbox: 'xbox.jpg',
  'face id': 'iphone.jpg',
  fingerprint: 'samsung.jpg',
  x: 'x-twitter.jpg',
  threads: 'threads.jpg',
  bereal: 'bereal.jpg',
  clubhouse: 'clubhouse.jpg',
  'x spaces': 'x-spaces.jpg',
  fawry: 'fawry.jpg',
  instapay: 'instapay.jpg',
  paypal: 'financial-freedom.jpg',
  'apple pay': 'iphone.jpg',
  swvl: 'swvl-v2.jpg',
  microbus: 'microbus-v2.jpg',
  'wi-fi': 'wifi.jpg',
  alarm: 'alarm-clock-v2.jpg',
  'body clock': 'body-clock-v2.jpg',
  'hire maid': 'maid-service-v2.jpg',
  'do it yourself': 'diy-cleaning-v2.jpg',
  'abaya style': 'abaya-v2.jpg',
  'souq friday': 'souq.jpg',
  'souq deals': 'souq.jpg',
  'black friday': 'black-friday.jpg',
  'gift card': 'gift-card.jpg',
  'gift cards': 'gift-card.jpg',
  drive: 'driving.jpg',
  cook: 'cooking.jpg',
  cater: 'fancy-restaurant.jpg',
  buffet: 'buffet.jpg',
  'à la carte': 'a-la-carte.jpg',
  podcast: 'spotify.jpg',
  radio: 'spotify.jpg',
  notion: 'notion.jpg',
  'google docs': 'google-docs.jpg',
  'e-book': 'books.jpg',
  'physical book': 'books.jpg',
  'online courses': 'linkedin.jpg',
  university: 'books.jpg',
  linkedin: 'linkedin.jpg',
  cinema: 'cinema.jpg',
  drone: 'camping.jpg',
  'action camera': 'camping.jpg',
  electric: 'bmw.jpg',
  petrol: 'toyota.jpg',
  console: 'playstation.jpg',
  pc: 'wfh.jpg',
  'qr code': 'iphone.jpg',
  tablet: 'iphone.jpg',
  laptop: 'wfh.jpg',
  speaker: 'bose.jpg',
  headphones: 'bose.jpg',
  online: 'iphone.jpg',
  mobile: 'iphone.jpg',
  'dark mode': 'chatgpt.jpg',
  'light mode': 'iphone.jpg',
  'two phones': 'samsung.jpg',
  'one phone': 'iphone.jpg',
  crypto: 'crypto.jpg',
  bank: 'financial-freedom.jpg',
  canon: 'camping.jpg',
  'phone camera': 'phone-camera.jpg',
  dell: 'wfh.jpg',
  hp: 'wfh.jpg',
  'gadget lover': 'iphone.jpg',

  // Eat & Drink
  'eat out': 'fancy-restaurant.jpg',
  'cook at home': 'home-dinner.jpg',
  starbucks: 'starbucks.jpg',
  'local coffee': 'turkish-coffee.jpg',
  costa: 'starbucks.jpg',
  'tim hortons': 'starbucks.jpg',
  "mcdonald's": 'mcdonalds.jpg',
  'burger king': 'burger-king.jpg',
  "hardee's": 'hardees.jpg',
  tea: 'tea.jpg',
  coffee: 'coffee.jpg',
  pizza: 'pizza.jpg',
  sushi: 'sushi.jpg',
  falafel: 'falafel.jpg',
  hummus: 'hummus.jpg',
  koshary: 'koshary.jpg',
  shawarma: 'shawarma.jpg',
  kunafa: 'kunafa.jpg',
  basbousa: 'kunafa.jpg',
  dates: 'dates.jpg',
  chocolate: 'chocolate.jpg',
  'dark chocolate': 'dark-chocolate.jpg',
  'milk chocolate': 'milk-chocolate.jpg',
  'turkish coffee': 'turkish-coffee.jpg',
  espresso: 'coffee.jpg',
  manakeesh: 'manaeesh.jpg',
  "mana'eesh": 'manaeesh.jpg',
  croissant: 'croissant.jpg',
  grilled: 'grilled.jpg',
  fried: 'fried.jpg',
  'grilled chicken': 'grilled.jpg',
  'fried chicken': 'fried.jpg',
  'street food': 'falafel.jpg',
  'fine dining': 'fancy-restaurant.jpg',
  delivery: 'noon.jpg',
  'dine in': 'fancy-restaurant.jpg',
  lebanese: 'hummus.jpg',
  vegan: 'falafel.jpg',
  'meat lover': 'grilled.jpg',
  'ice cream': 'ice-cream.jpg',
  brunch: 'croissant.jpg',
  'skip to lunch': 'grilled.jpg',
  'food market': 'falafel.jpg',
  supermarket: 'shopping.jpg',
  nuts: 'dates.jpg',
  chips: 'chips.jpg',
  spicy: 'grilled.jpg',
  mild: 'hummus.jpg',
  'protein shake': 'gym.jpg',
  'fresh juice': 'dates.jpg',
  'meal prep': 'home-dinner.jpg',
  'cook fresh': 'grilled.jpg',
  water: 'nature.jpg',
  'soft drink': 'pepsi.jpg',
  'eat alone': 'coffee.jpg',
  'with people': 'fancy-restaurant.jpg',
  'smoothie bowl': 'dates.jpg',
  cereal: 'croissant.jpg',
  'always dessert': 'kunafa.jpg',
  rarely: 'grilled.jpg',
  'skip breakfast': 'coffee.jpg',
  'never skip': 'croissant.jpg',
  leftovers: 'home-dinner.jpg',
  'always fresh': 'grilled.jpg',
  view: 'fancy-restaurant.jpg',
  'hidden gem': 'falafel.jpg',
  homemade: 'dates.jpg',
  bottled: 'pepsi.jpg',
  sahlab: 'turkish-coffee.jpg',
  'hot chocolate': 'chocolate.jpg',
  matcha: 'matcha.jpg',
  foul: 'foul.jpg',
  eggs: 'eggs.jpg',
  // buffet and à la carte already defined above
  'follow recipe': 'books.jpg',
  improvise: 'home-dinner.jpg',
  'all you can eat': 'grilled.jpg',
  quality: 'fancy-restaurant.jpg',
  breakfast: 'croissant.jpg',
  dinner: 'fancy-restaurant.jpg',
  'cooking show': 'netflix.jpg',
  'food vlogger': 'tiktok.jpg',
  sparkling: 'starbucks.jpg',
  still: 'nature.jpg',
  'eat healthy': 'falafel.jpg',
  'eat happy': 'pizza.jpg',
  iced: 'starbucks.jpg',
  hot: 'turkish-coffee.jpg',
  takeaway: 'noon.jpg',
  'eat in': 'fancy-restaurant.jpg',
  seafood: 'seafood.jpg',
  'red meat': 'grilled.jpg',
  'food truck': 'falafel.jpg',
  restaurant: 'fancy-restaurant.jpg',
  'chai karak': 'chai-karak.jpg',
  cappuccino: 'coffee.jpg',
  'molten chocolate': 'chocolate.jpg',
  'el reem': 'shawarma.jpg',
  'bab el hara': 'shawarma.jpg',
  sobia: 'dates.jpg',
  'qamar el din': 'dates.jpg',

  // Spending & Money
  save: 'financial-freedom.jpg',
  'spend now': 'shopping.jpg',
  'buy a car': 'bmw.jpg',
  invest: 'stocks.jpg',
  rent: 'city-apartment.jpg',
  'buy apartment': 'real-estate.jpg',
  startup: 'wfh.jpg',
  'corporate job': 'suit.jpg',
  freelance: 'wfh.jpg',
  'full time': 'suit.jpg',
  'one big purchase': 'branded.jpg',
  'many small': 'shopping.jpg',
  'credit card': 'shopping.jpg',
  cash: 'financial-freedom.jpg',
  'gold bars': 'gold-bars.jpg',
  'real estate': 'real-estate.jpg',
  'side hustle': 'wfh.jpg',
  focus: 'suit.jpg',
  'budget travel': 'fly.jpg',
  'luxury travel': 'hilton.jpg',
  'designer brand': 'branded.jpg',
  'no-name quality': 'shopping.jpg',
  'salary job': 'suit.jpg',
  'own business': 'wfh.jpg',
  'study abroad': 'fly.jpg',
  'local university': 'books.jpg',
  'financial freedom': 'financial-freedom.jpg',
  mba: 'mba.jpg',
  'first class': 'first-class.jpg',
  budget: 'financial-freedom.jpg',
  luxury: 'hilton.jpg',
  gold: 'gold-bars.jpg',
  stocks: 'stocks.jpg',
  wedding: 'big-wedding.jpg',
  house: 'real-estate.jpg',
  international: 'international-brand.jpg',
  local: 'local-brand.jpg',
  split: 'fancy-restaurant.jpg',
  'one pays': 'financial-freedom.jpg',

  // Everyday Life
  'early riser': 'sunrise.jpg',
  'night owl': 'night-sky.jpg',
  'early bird': 'day-sky.jpg',
  gym: 'gym.jpg',
  outdoor: 'outdoor-workout.jpg',
  'big wedding': 'big-wedding.jpg',
  intimate: 'intimate-wedding.jpg',
  compound: 'compound.jpg',
  'city apartment': 'city-apartment.jpg',
  wfh: 'wfh.jpg',
  office: 'suit.jpg',
  'work from home': 'wfh.jpg',
  read: 'books.jpg',
  watch: 'movies.jpg',
  'move abroad': 'move-abroad.jpg',
  'stay home': 'home-dinner.jpg',
  beach: 'beach.jpg',
  mountain: 'mountains.jpg',
  mountains: 'mountains.jpg',
  summer: 'summer.jpg',
  winter: 'winter.jpg',
  sunrise: 'sunrise.jpg',
  sunset: 'sunset.jpg',
  city: 'city.jpg',
  nature: 'nature.jpg',
  morning: 'sunrise.jpg',
  night: 'night.jpg',
  dogs: 'dogs.jpg',
  cats: 'cats.jpg',
  dog: 'dogs.jpg',
  cat: 'cats.jpg',
  introvert: 'books.jpg',
  extrovert: 'going-out.png',
  homebody: 'home-dinner.jpg',
  'always out': 'going-out.png',
  solo: 'alone-shopping.jpg',
  group: 'going-out.png',
  minimalist: 'nature.jpg',
  maximalist: 'branded.jpg',
  text: 'iphone.jpg',
  call: 'iphone.jpg',
  'travel light': 'fly.jpg',
  'pack everything': 'pack-everything.jpg',
  strict: 'suit.jpg',
  flexible: 'wfh.jpg',
  staycation: 'home-dinner.jpg',
  travel: 'fly.jpg',
  music: 'movies.jpg',
  silence: 'books.jpg',
  'large group': 'going-out.png',
  'small circle': 'coffee.jpg',
  paper: 'books.jpg',
  digital: 'iphone.jpg',
  routine: 'suit.jpg',
  spontaneous: 'fly.jpg',
  journal: 'books.jpg',
  'mental notes': 'iphone.jpg',
  meditation: 'nature.jpg',
  'more sleep': 'night-sky.jpg',
  // alarm and body clock already defined above
  // drive already defined above
  'be driven': 'uber.png',
  // cook already defined above
  'order in': 'order-in.jpg',
  couple: 'gym.jpg',
  'news junkie': 'news-junkie.jpg',
  'news detox': 'nature.jpg',
  // cater already defined above
  walk: 'nature.jpg',
  camping: 'camping.jpg',
  hotel: 'hotel.jpg',
  garden: 'compound.jpg',
  penthouse: 'city-apartment.jpg',
  'road trip': 'city.jpg',
  fly: 'fly.jpg',
  // hire maid and do it yourself already defined above

  // Style
  nike: 'nike.jpg',
  adidas: 'adidas.jpg',
  zara: 'zara.jpg',
  'h&m': 'hm.jpg',
  sneakers: 'sneakers.jpg',
  boots: 'boots.jpg',
  'formal shoes': 'dress-shoes.jpg',
  books: 'books.jpg',
  'gold jewelry': 'rolex.jpg',
  'silver jewelry': 'silver-jewelry.jpg',
  balenciaga: 'balenciaga.jpg',
  'off-white': 'off-white.jpg',
  thobe: 'thobe.jpg',
  'hijab fashion': 'hijab-fashion-v2.jpg',
  // abaya style already defined above
  ounass: 'branded.jpg',
  farfetch: 'branded.jpg',
  converse: 'converse.jpg',
  vans: 'vans.jpg',
  'designer sunglasses': 'designer.jpg',
  'local designer': 'local-brand.jpg',
  'international brand': 'international-brand.jpg',
  'minimal makeup': 'natural-beauty.jpg',
  'full glam': 'designer.jpg',
  'follow trends': 'follow-trends.jpg',
  'own style': 'branded.jpg',

  // Brands
  pepsi: 'pepsi.jpg',
  'coca-cola': 'coca-cola.jpg',
  bmw: 'bmw.jpg',
  mercedes: 'mercedes.jpg',
  audi: 'audi.jpg',
  toyota: 'toyota.jpg',
  rolex: 'rolex.jpg',
  casio: 'casio.jpg',
  apple: 'iphone.jpg',
  sony: 'bose.jpg',
  bose: 'bose.jpg',
  kfc: 'kfc.jpg',
  popeyes: 'popeyes.jpg',
  ikea: 'ikea.jpg',
  'louis vuitton': 'louis-vuitton.jpg',
  gucci: 'gucci.jpg',
  versace: 'versace.jpg',
  'd&g': 'versace.jpg',
  'ray-ban': 'ray-ban.jpg',
  oakley: 'ray-ban.jpg',
  nespresso: 'coffee.jpg',
  'turkish pot': 'turkish-pot.jpg',
  hilton: 'hilton.jpg',
  marriott: 'hotel.jpg',
  airbnb: 'airbnb.jpg',
  'uber eats': 'uber-eats.jpg',
  gopro: 'camping.jpg',
  wework: 'linkedin.jpg',
  'home office': 'wfh.jpg',
  uniqlo: 'zara.jpg',
  lululemon: 'gym.jpg',
  'under armour': 'gym.jpg',
  reebok: 'sneakers.jpg',
  puma: 'puma.jpg',
  sephora: 'hijab-fashion.jpg',
  'local shop': 'local-brand.jpg',
  'samsung tv': 'samsung.jpg',
  lg: 'samsung.jpg',
  jordan: 'nike.jpg',
  yeezy: 'adidas.jpg',
  "domino's": 'pizza.jpg',
  'local pizza': 'pizza.jpg',
  dyson: 'ikea.jpg',
  'local brand': 'local-brand.jpg',
  weber: 'grilled.jpg',
  'local grill': 'grilled.jpg',
  moleskine: 'books.jpg',
  'any notebook': 'books.jpg',
  'north face': 'mountains.jpg',
  lego: 'playstation.jpg',
  'local toys': 'playstation.jpg',
  'baskin-robbins': 'ice-cream.jpg',
  'local gelato': 'kunafa.jpg',
  'red bull': 'red-bull.jpg',
  monster: 'red-bull.jpg',
  "lay's": 'chips.jpg',
  pringles: 'chips.jpg',
  cheetos: 'chips.jpg',
  gillette: 'suit.jpg',
  'local razor': 'suit.jpg',
  pampers: 'home-dinner.jpg',
  lipton: 'tea.jpg',
  'ahmad tea': 'tea.jpg',
  nutella: 'nutella.jpg',
  'local chocolate spread': 'chocolate.jpg',
  oud: 'oud.jpg',
  fresh: 'fresh-perfume.jpg',

  // Shopping
  'online shop': 'shopping.jpg',
  'brand store': 'brand-store.jpg',
  branded: 'branded.jpg',
  unbranded: 'shopping.jpg',
  alone: 'alone-shopping.jpg',
  'with friends': 'going-out.png',
  // black friday and souq friday already defined above
  'normal prices': 'mall.jpg',
  shopping: 'shopping.jpg',
  'window shop': 'window-shop.jpg',
  'buy immediately': 'shopping.jpg',
  // gift cards already defined above
  'cash gifts': 'financial-freedom.jpg',
  // gift card already defined above
  'picked gift': 'pick-gift.jpg',
  'pick gift': 'pick-gift.jpg',
  'duty free': 'duty-free.jpg',
  'return': 'shopping.jpg',
  'keep it': 'branded.jpg',
  'read reviews': 'iphone.jpg',
  'trust instinct': 'branded.jpg',
  'cash on delivery': 'shopping.jpg',
  prepay: 'iphone.jpg',
  'try first': 'mall.jpg',
  'trust online': 'iphone.jpg',
  mall: 'mall.jpg',
  'in-store': 'mall.jpg',

  // Cairo & MENA Local
  cairo: 'cairo.jpg',
  'city stars': 'city-stars-mall.jpg',
  'mall of arabia': 'mall-of-arabia.jpg',
  'abu dhabi': 'abu-dhabi.jpg',
  riyadh: 'abu-dhabi.jpg',
  jeddah: 'dubai-visit.jpg',
  'egyptian': 'egyptian-series.jpg',
  khaleeji: 'dubai-visit.jpg',
  turkish: 'turkish-series.jpg',
  alexandria: 'alexandria.jpg',
  sahel: 'sahel.jpg',
  maadi: 'cairo.jpg',
  heliopolis: 'cairo.jpg',
  zamalek: 'cairo.jpg',
  'new cairo': 'compound.jpg',
  dahab: 'beach.jpg',
  sharm: 'ain-sokhna.jpg',
  gouna: 'gouna.jpg',
  'ain sokhna': 'ain-sokhna.jpg',
  marina: 'marina.jpg',
  metro: 'metro.jpg',
  'nile cruise': 'nile-cruise.jpg',
  felucca: 'felucca.jpg',
  'nights out': 'going-out.png',
  'friday brunch': 'fancy-restaurant.jpg',
  'sahel weekend': 'sahel.jpg',
  'henna night': 'night.jpg',
  'bachelor party': 'going-out.png',
  private: 'books.jpg',
  public: 'books.jpg',
  'egyptian wedding': 'big-wedding.jpg',
  destination: 'fly.jpg',
  'live there': 'city-apartment.jpg',
  'visit only': 'dubai-visit.jpg',
  'eid shopping': 'shopping.jpg',
  'eid travel': 'fly.jpg',
  ahly: 'ahly.jpg',
  'al ahly': 'ahly.jpg',

  // Style - additional
  heels: 'heels.jpg',
  flats: 'flats.jpg',
  loungewear: 'loungewear.jpg',
  denim: 'denim.jpg',
  backpack: 'backpack.jpg',
  tote: 'tote.jpg',
  'designer bag': 'designer-bag.jpg',
  monochrome: 'monochrome.jpg',
  'all black': 'monochrome.jpg',
  'smart casual': 'smart-casual.jpg',
  oversized: 'oversized.jpg',
  fitted: 'smart-casual.jpg',
  aviator: 'aviator.jpg',
  wayfarer: 'wayfarer.jpg',
  'new balance': 'new-balance.jpg',
  capsule: 'capsule-wardrobe.jpg',
  collection: 'thrift.jpg',
  'dress shoes': 'dress-shoes.jpg',
  'dress up': 'designer.jpg',
  'eco-friendly': 'eco-friendly.jpg',
  silver: 'silver-jewelry.jpg',
  bracelet: 'silver-jewelry.jpg',
  thrift: 'thrift.jpg',
  'second-hand': 'thrift.jpg',
  'brand new': 'brand-store.jpg',
  'always new': 'brand-store.jpg',
  leather: 'designer-bag.jpg',
  'vegan leather': 'eco-friendly.jpg',
  'indie label': 'local-brand.jpg',
  statement: 'designer.jpg',
  subtle: 'smart-casual.jpg',
  bold: 'designer.jpg',
  plain: 'smart-casual.jpg',
  prints: 'thrift.jpg',
  colored: 'thrift.jpg',
  colors: 'thrift.jpg',
  classics: 'capsule-wardrobe.jpg',
  matching: 'smart-casual.jpg',
  inspired: 'designer.jpg',
  original: 'branded.jpg',
  'one good pair': 'dress-shoes.jpg',
  white: 'sneakers.jpg',

  // Spending & Money - additional
  insurance: 'insurance.jpg',
  'emergency fund': 'insurance.jpg',
  'savings account': 'financial-freedom.jpg',
  'invest early': 'stocks.jpg',
  'invest in self': 'linkedin.jpg',
  'retire early': 'financial-freedom.jpg',
  'work forever': 'linkedin.jpg',
  'salary abroad': 'fly.jpg',
  'new car': 'bmw.jpg',
  'used car': 'toyota.jpg',
  'enjoy now': 'shopping.jpg',
  'enjoy 20s': 'going-out.png',
  'save money': 'financial-freedom.jpg',
  'spend freely': 'shopping.jpg',
  'yolo fund': 'shopping.jpg',
  'dream job': 'linkedin.jpg',
  'corporate ladder': 'suit.jpg',
  corporate: 'suit.jpg',
  negotiate: 'suit.jpg',
  'generous tip': 'fancy-restaurant.jpg',
  'risk it': 'crypto.jpg',
  'invest all': 'stocks.jpg',
  advisor: 'linkedin.jpg',
  'co-founder': 'wfh.jpg',
  finance: 'financial-freedom.jpg',
  money: 'financial-freedom.jpg',
  'gym membership': 'gym.jpg',
  'free workout': 'outdoor-workout.jpg',
  subscribe: 'iphone.jpg',
  subscription: 'iphone.jpg',
  'pay per use': 'shopping.jpg',
  'one-time': 'shopping.jpg',
  'buy now': 'shopping.jpg',

  // Everyday Life - additional
  'luxury vacation': 'hilton.jpg',
  experiences: 'fly.jpg',
  multitask: 'wfh.jpg',
  'single focus': 'books.jpg',
  'new skill': 'linkedin.jpg',
  'self-taught': 'books.jpg',
  researcher: 'books.jpg',
  passion: 'nature.jpg',
  'set own': 'wfh.jpg',
  language: 'language.jpg',
  arabic: 'cairo.jpg',
  english: 'linkedin.jpg',
  iron: 'suit.jpg',
  'wrinkle-free': 'smart-casual.jpg',

  // Shopping - additional
  'compare prices': 'iphone.jpg',
  impulse: 'shopping.jpg',
  wishlists: 'iphone.jpg',
  'buy on sight': 'shopping.jpg',
  'buy trusted': 'brand-store.jpg',
  'just buy': 'shopping.jpg',
  'reviews first': 'iphone.jpg',
  'wait for sale': 'shopping.jpg',
  // souq deals already defined above
  'free shipping': 'noon-brand.jpg',
  'same day': 'talabat.jpg',
  'return often': 'shopping.jpg',
  'keep it longer': 'branded.jpg',
  'keep all': 'branded.jpg',
  'new arrivals': 'brand-store.jpg',
  bulk: 'buy-bulk.jpg',
  'buy bulk': 'buy-bulk.jpg',
  'as needed': 'shopping.jpg',
  hypermarket: 'shopping.jpg',
  'local market': 'falafel.jpg',
  'worth it': 'branded.jpg',
  'not worth it': 'shopping.jpg',
  'best deal': 'shopping.jpg',
  cheapest: 'shopping.jpg',
  variety: 'thrift.jpg',
  'every year': 'fly.jpg',
  'home comfort': 'home-dinner.jpg',

  // Food - additional
  sugar: 'kunafa.jpg',
  'sugar-free': 'dates.jpg',
  cold: 'ice-cream.jpg',
  regular: 'coffee.jpg',
  standard: 'coffee.jpg',
  'street': 'falafel.jpg',
  'home dinner': 'home-dinner.jpg',
};

interface PollImageParams {
  genericFallback?: string;
  imageUrl?: string | null;
  option?: string | null;
  question?: string | null;
  side: PollImageSide;
}

function normalize(value?: string | null) {
  return (value || '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
}

function slugify(value?: string | null) {
  return normalize(value).replace(/\s+/g, '-');
}

function getLocalImageByName(fileName?: string | null) {
  if (!fileName) return undefined;
  return localPollImages[fileName.toLowerCase()];
}

function getLocalImageBySlug(value?: string | null) {
  const slug = slugify(value);
  if (!slug) return undefined;

  for (const ext of ['jpg', 'png', 'jpeg', 'webp', 'avif']) {
    const match = getLocalImageByName(`${slug}.${ext}`);
    if (match) return match;
  }

  return undefined;
}

function getQuestionAliasImage(question?: string | null, side?: PollImageSide) {
  const aliasFile = QUESTION_SIDE_ALIASES[normalize(question)]?.[side ?? 'A'];
  return getLocalImageByName(aliasFile);
}

function getOptionAliasImage(option?: string | null) {
  return getLocalImageByName(OPTION_ALIASES[normalize(option)]);
}

function extractFilename(url?: string | null) {
  if (!url) return null;

  try {
    const parsed = new URL(url);
    const fileName = parsed.pathname.split('/').pop();
    return fileName ? decodeURIComponent(fileName).toLowerCase() : null;
  } catch {
    const cleaned = url.split('?')[0].split('#')[0];
    const fileName = cleaned.split('/').pop();
    return fileName ? decodeURIComponent(fileName).toLowerCase() : null;
  }
}

function isStoragePollImageUrl(url?: string | null) {
  return !!url && url.includes('/storage/v1/object/public/poll-images/');
}

function getPreferredLocalImage({ question, option, side }: PollImageParams) {
  return (
    getQuestionAliasImage(question, side) ||
    getLocalImageBySlug(option) ||
    getOptionAliasImage(option)
  );
}

// Deterministic generic fallback from local assets pool
function getGenericFallback(seed?: string | null): string {
  const allLocal = Object.values(localPollImages);
  if (allLocal.length === 0) return '';
  const hash = (seed || 'x').split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  return allLocal[hash % allLocal.length];
}

export function getPollImageFallbackSrc(params: PollImageParams) {
  const preferredLocal = getPreferredLocalImage(params);
  if (preferredLocal) return preferredLocal;

  const sourceLocal = getLocalImageByName(extractFilename(params.imageUrl));
  if (sourceLocal) return sourceLocal;

  return params.genericFallback || getGenericFallback(params.option || params.question);
}

export function getPollDisplayImageSrc(params: PollImageParams) {
  const preferredLocal = getPreferredLocalImage(params);
  if (preferredLocal) return preferredLocal;

  if (params.imageUrl) {
    const sourceLocal = getLocalImageByName(extractFilename(params.imageUrl));
    if (sourceLocal) return sourceLocal;

    // Only return the raw URL if it's NOT a storage URL (e.g. Unsplash works fine)
    if (!isStoragePollImageUrl(params.imageUrl)) {
      return params.imageUrl;
    }
    // Storage URLs are known to be broken — fall through to generic fallback
  }

  return params.genericFallback || getGenericFallback(params.option || params.question);
}

/** onError handler for img tags — swaps to local fallback */
export function handlePollImageError(
  e: React.SyntheticEvent<HTMLImageElement>,
  params: Omit<PollImageParams, 'imageUrl'>
) {
  const target = e.currentTarget;
  if (target.dataset.fallbackApplied) return; // prevent infinite loop
  target.dataset.fallbackApplied = 'true';
  const fallback = getPollImageFallbackSrc({ ...params, imageUrl: target.src });
  if (fallback) {
    target.src = fallback;
  }
}
